### ISSUE TITLE
Arrange Library Officers alphabetically

### ISSUE THREAD

**Issue by tobolar** [modelica/MAP-LIB_ProjectRules#17]
As there exists no role of "main" Library Officer, I suggest to arrange Library Officers in Annex 3 in alphabetical order.

**Comment by dietmarw** [comment]
By first or last name?

**Comment by tobolar** [comment]
:-D How do we like it? To me this should be by surname.

**Comment by dietmarw** [comment]
But I always lose that way :smirk: . But OK, feel free to send a PR not sure when I can get to it myself.
