### ISSUE TITLE
Shall there be a library officer assigned to Modelica.UsersGuide?

### ISSUE THREAD

**Issue by christiankral** [modelica/MAP-LIB_ProjectRules#21]
It's seems there is no Library Officer assigned to `Modelica.UsersGuide`. No one is listed in on [MAP-LIB_ProjectRules.md](https://github.com/modelica/MAP-LIB_ProjectRules/blob/master/MAP-LIB_ProjectRules.md) nor in the [Modelica.UsersGuide](https://doc.modelica.org/Modelica%203.2.3/Resources/helpOM/Modelica.UsersGuide.html) itself.

Is this made intentionally? I suppose it also makes sense have some responsible library officers for this package. I am willing to serve as library officer for the User's Guide as I already contributed some documentation there.

**Comment by beutlich** [comment]
Yes, this would be very helpful. Can I kindly ask you and @tobolar to take over these responsibility?

**Comment by christiankral** [comment]
That's perfectly fine with me.

**Comment by tobolar** [comment]
I agree as well. Let' see how the situation envelopes.
